server:
  port: 6001
#连接数据库信息
spring:
  #配置数据源
  datasource:
    #配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    #配置连接数据库的信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.131:3306/ssg?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis:
    database: 0
    host: 192.168.10.131
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0